name: Sync to test-YAF2026

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to test-YAF2026
        run: |
          git remote add target https://x-access-token:${{ secrets.TARGET_TOKEN }}@github.com/tokyo-sokayouth/test-YAF2026.git
          git push target main --force
